"""Initial db table

Revision ID: 3fc0879ca72
Revises: None
Create Date: 2015-02-27 15:09:16.333191

"""

# revision identifiers, used by Alembic.
revision = '3fc0879ca72'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('review_patchset', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), index=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result')
    ### end Alembic commands ###
